### PR TITLE
Fix #491: Validate against binary data in non-body container parameters

### LINKED ISSUE #491: Conjure generator accepts invalid query parameter types
## What happened?
Ran the Conjure generator on the following definition, and it succeeded/generated IR without any errors:

```yml
services:
  TestService:
    name: Test Service
    package: api
    endpoints:
      queryParamListBinary:
        http: GET /binaryListQueryVar
        args:
          myQueryParam1:
            type: list<binary>
            param-type: query
```

## What did you want to happen?
CLI should report that the definition is invalid/illegal and fail, as, per the [Conjure definition document](https://github.com/palantir/conjure/blob/master/docs/spec/conjure_definitions.md#argumentdefinition), query parameters cannot be binary (or a container of it):

> If the param-type is query then the de-aliased type MUST be an enum or a primitive (except binary and bearertoken), or a container (list, set, optional) of one of these.

### PR DESCRIPTION
**Pull request by carterkozak**
## Before this PR
Query and header parameters using `list<binary>` `set<binary>` and `optional<binary>` types incorrectly passed validation.

## After this PR
==COMMIT_MSG==
Validate against binary data in non-body container parameters.
==COMMIT_MSG==

### CODE REVIEW

File: conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java [hunk 1]
```diff
@@ -100,17 +101,32 @@ public void validate(EndpointDefinition definition, DealiasingTypeVisitor dealia
...
+            if (input.accept(TypeVisitor.IS_OPTIONAL)) {
+                return validateType(input.accept(TypeVisitor.OPTIONAL).getItemType(), dealiasingTypeVisitor);
+            }
+            if (input.accept(TypeVisitor.IS_LIST)) {
+                return validateType(input.accept(TypeVisitor.LIST).getItemType(), dealiasingTypeVisitor);
+            }
+            if (input.accept(TypeVisitor.IS_SET)) {
+                return validateType(input.accept(TypeVisitor.SET).getItemType(), dealiasingTypeVisitor);
+            }
+            return !type.accept(TypeVisitor.IS_BINARY) && !type.accept(TypeVisitor.IS_ANY);
```
Comment (nmiyake) [inline conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: Not sure if this should be handled in a separate PR, but for query and path parameters, the check should also reject containers that contain `bearertoken`.

File: conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java [hunk 2]
```diff
@@ -100,17 +101,32 @@ public void validate(EndpointDefinition definition, DealiasingTypeVisitor dealia
...
-                        boolean isValid = dealiasingTypeVisitor.dealias(arg.getType())
-                                .fold(
-                                        typeDefinition -> true,
-                                        type -> !type.accept(TypeVisitor.IS_BINARY)
-                                                && !type.accept(TypeVisitor.IS_ANY)
-                                );
                         Preconditions.checkArgument(
-                                isValid, "Non body parameters cannot be of the 'binary' type: '%s' is not allowed",
+                                validateType(arg.getType(), dealiasingTypeVisitor),
+                                "Non body parameters cannot be of the 'binary' type: '%s' is not allowed",
```
Comment (nmiyake) [inline conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: "cannot reference the 'binary' type" might be a bit more accurate, since `list<binary>` is technically not the binary type.

Comment (nmiyake) [reply conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: Would it also be possible to print the actual type definition in the error message (`list<binary>` etc.)? If so, I think that would make the error message a bit more user-friendly.

Comment (carterkozak) [reply conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: Good call. Rendering the human-readable type definition isn't trivial, but I've added the endpoint name and path for easier debugging.

File: conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java [hunk 3]
```diff
@@ -99,17 +100,32 @@ public void validate(EndpointDefinition definition, DealiasingTypeVisitor dealia
...
+
+        private static boolean validateType(Type input, DealiasingTypeVisitor dealiasingTypeVisitor) {
+            Optional<Type> dealiased = dealiasingTypeVisitor.dealias(input)
+                    .fold(typeDefinition -> Optional.empty(), Optional::of);
+            // typeDef isn't binary
+            if (!dealiased.isPresent()) {
+                return true;
+            }
+            Type type = dealiased.get();
+            if (input.accept(TypeVisitor.IS_OPTIONAL)) {
```
Comment (iamdanfox) [inline conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: rather than a chain of if statements here, shall we just use a Type.Visitor so that it's guaranteed to be exhaustive?

Comment (carterkozak) [reply conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: The visitor creates a lot of duplication with the dealiasing visitor and requires us to handle types that are already disallowed elsewhere (map). I think the current code is easier to follow, but it would be more difficult to find if we added new container types.

Comment (iamdanfox) [reply conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java]: OK fair enough - guess we're not at particular risk from that as no new collection types coming down the pipeline!

**Comment by carterkozak** [comment]
Dozer?
